### ISSUE TITLE
Muerte a los motores de templates en python

### ISSUE THREAD

**Issue by elleryeng** [py-mx/Charlas#10]
Descripción: Olvídate de embeber código de diferentes lenguajes en tus archivos HTML, incluso cuando se trate de presentar los resultados de una base de datos. 

Objetivo: Veremos como hacer sustituciones estáticas y dinámicas sobre archivos HTML solo con la librería estándar de python

Ellery Eng - Me gusta el desarrollo web, python linux y la fotografía 
eng.ellery@gmail.com

**Comment by pixelead0** [comment]
Grabación de la charla disponible en: https://www.youtube.com/watch?v=6cOv8ogfpQk
