### ISSUE TITLE
Automatización de pruebas unitarias y E2E con Python + Selenium

### ISSUE THREAD

**Issue by terranigmark** [py-mx/Charlas#12]
**Nombre de la propuesta:** Automatización de pruebas unitarias y E2E con Python + Selenium
**Descripción(en caso de ser propuesta):** La automatización está para ayudarnos con las tareas que son repetitivas, especialmente cuando podemos hacerlo con nuestro lenguaje favorito.
Objetivo(aplica a todos): Aprenderás a crear tus primeras pruebas unitarias, End to End (E2E) y generar reportes que cualquier persona puede entender con Python y la capacidad de automatización de Selenium.
**Breve reseña sobre ti(en caso de ser propuesta):** Online Community Realtions en Platzi, apasionado por la tecnología, entusiasta de brindar la mejor experiencia a usuarios a través del Automation Testing.
**Correo electrónico:** linnk99@gmail.com

**Comment by Develop5** [comment]
Hola, 
Me acabo de incorporar aquí. ¿Esta charla se efectuó? ¿Existe una grabación?
Gracias.

**Comment by pixelead0** [comment]
Sí, puedes ver el video en el canal de software gurú

https://www.youtube.com/watch?v=0-j547Fmy1A
