### ISSUE TITLE
Cómo crear una api serveless con flask y aws

### ISSUE THREAD

**Issue by BetMG** [py-mx/Charlas#13]
Nombre de la propuesta: Cómo crear una api serveless con flask y aws
Descripción(en caso de ser propuesta): caso práctico de una api serveless utilizando flask, lambda function y api gateway (aws)
Objetivo(aplica a todos): aprender a hacer una api serveless sencilla 
Breve reseña sobre ti(en caso de ser propuesta): Desarrolladora fullstak en SocialPiper y emprendedora en los tiempos libres.
Correo electrónico: betsai.mendozagomez@gemail.com

**Comment by pixelead0** [comment]
grabación de la charla disponible en: https://www.youtube.com/watch?v=CCykxREwguY
