### ISSUE TITLE
Mi primer paquete en Pypi

### ISSUE THREAD

**Issue by andrscyv** [py-mx/Charlas#14]
Nombre de la propuesta: Mi primer paquete en Pypi 
Descripción(en caso de ser propuesta): Relatar como es el proceso para subir un pequeño paquete para hacer web scrapping de la busqueda de youtube a Pypi
Objetivo(aplica a todos): Aprenderas el proceso básico para subir un paquete a Pypi así como 
algunos tips de los errores que yo cometí 
Breve reseña sobre ti(en caso de ser propuesta): Desarrollador fullstack con Js y python. Freelancer
Correo electrónico: andrscyv@gmail.com

**Comment by pixelead0** [comment]
Grabación de la charla disponible en: https://www.youtube.com/watch?v=ubKHai_JF7w
