### ISSUE TITLE
Entendiendo el cálculo de polaridad con etiquetado POS y SentiWordNet

### ISSUE THREAD

**Issue by JesusTitla** [py-mx/Charlas#15]
Nombre de la propuesta: Entendiendo el cálculo de polaridad con etiquetado POS y SentiWordNet
Descripción(en caso de ser propuesta): Esquema sencillo para calcular polaridad positiva/negativa de una frase.
Objetivo(aplica a todos): Entender un esquema sencillo para calcular polaridad (positiva/negativa) de una frase usando etiquetado de Partes De la Oración y SentiWordNet.
Breve reseña sobre ti(en caso de ser propuesta): Estudiante de maestría, entusiasta de ML y DL
Correo electrónico: jesus.r.titla@gmail.com

**Comment by pixelead0** [comment]
Hola @JesusTitla, estaremos retomando nuevamente los meetups, presenciales en la cdmx, si aún deses dar esta charla por favor contactame.
