### ISSUE TITLE
Serverless con Zappa: más allá del Hola Mundo

### ISSUE THREAD

**Issue by ccdesales** [py-mx/Charlas#16]
Esta propuesta la escribí en ingles para una conferencia, pero por supuesto que para PyMX se puede hacer en español. 

Mi preferencia sería dar la charla un sábado a eso de las 13:00 por video conferencia ya que me encuentro en un huso horario diferente.

## Abstract

This talk will discuss non-trivial tips, pitfalls and best practices for Zappa framework, a popular tool for implementing Function As A Service (FAAS) on top of AWS Lambda. The topics covered here are often beyond introductory materials.

## Description

The Zappa framework is a useful tool for implementing low maintenance FAAS endpoints. Through a set of carefully thought default settings it provides a great deal of amount of functionality out of the box. At the same time, as projects grow bigger those defaults may turn against a developer with superficial knowledge of the underlying platform.

## Agenda:

- AWS API Gateway integration is a minefield:
  - The integration timeouts trap
  - Mapping RESTFul endpoints to Lambdas, good defaults gone wrong
- Using other AWS services
   - Security roles
- Timestamps and CPU: less control than you think on the underlying OS
- Memory: the conflict of using as little Lambdas as possible versus task footprint
- AWS Lambda Versioning and traffic splitting: desirable but not available
- CI/CD Pipelines: how to automate deployments without losing your cool
- Use separate staging environments: dev, staging, prod
- Using versions and canary releases
- The problem with compression, binary and Base64 results, in API Gateway
- Deployment env too big: have separate environments
- Save money with a Savings Plan

ccdesales@gmail.com

**Comment by pixelead0** [comment]
Hola @ccdesales, estaremos retomando nuevamente los meetups, presenciales en la cdmx, si aún deses dar esta charla por favor contactame.
