### ISSUE TITLE
Creando aplicaciones para la linea de comandos con python

### ISSUE THREAD

**Issue by andrscyv** [py-mx/Charlas#17]
Nombre de la propuesta: Haz tu propia aplicación para la línea de comandos con Python y Click
Descripción: Introducción a Click, una librería de python que nos permite hacer aplicaciones para la terminal
de forma sencilla y rápida.
Objetivo: Mostrar como hacer una cli con la librería Click
Breve reseña sobre mi: Ingeniero de Software freelance
Correo electrónico: andrscyv@gmail.com

**Comment by pixelead0** [comment]
Hola @andrscyv, estaremos retomando nuevamente los meetups, presenciales en la cdmx, si aún deses dar esta charla por favor contactame.
