### ISSUE TITLE
Experiencias Positivas y Aprendizaje en Python-docs-es

### ISSUE THREAD

**Issue by aroquega** [py-mx/Charlas#18]
Nombre de la propuesta: Experiencias Positivas y Aprendizaje en Python-docs-es

Descripción: 
En esta charla, hablo sobre el proyecto de python-docs-es y la experiencia de estar en el grupo: lo positivo de la comunidad, cómo es la amabilidad del grupo, por qué deberíamos contribuir al proyecto, y las habilidades técnicas que se pueden aprenden a pesar de ser un proyecto sobre traducción.

Objetivo: Incentivar a la audiencia a contribuir a python-docs-es.

Breve reseña sobre mí: Soy estudiante de universidad y mi primera contribución fue al proyecto de python-docs-es, tuve muchas dudas de si podía participar, al final me decidí y puedo contar la experiencia para que otras personas quieran participar.

Correo electrónico: aroquega@unsa.edu.pe | hristo.roqueg@gmail.com

**Comment by pixelead0** [comment]
Hola  @aroquega , estaremos retomando nuevamente los meetups, presenciales en la cdmx, si aún deses dar esta charla por favor contactame.

**Comment by aroquega** [comment]
hola Py-Mx/Charlas, disculpa pero creo que hace más de un año no estoy en
el proyecto, así que no podría la charla
