### ISSUE TITLE
Mi primer contribución al Open Source

### ISSUE THREAD

**Issue by vaquer** [py-mx/Charlas#2]
# Mi primer contribución al Open Source
**Descripción**:  Todos como desarrolladores hemos tenido la necesidad de generar una funcionalidad para la cual existe una librería que nos salva la vida. Pero alguna vez nos hemos preguntado ¿Y si las personas que están detrás de esa llibreria dejarán de mantenerla?, ¿Y si pudiera apoyar al desarrollo de la misma?. Todos podemos hacer algo para que los esfuerzos del Open Source sigan brindando felicidad a los programadores y sus usuarios.
**Objetivo**: Motivar a la contribución en los proyectos Open Source.
```
$ whoami
Francisco Vaquero Ciciliano
Ingeniero en Informatica del Politecnico UPIICSA
Software Engineer en OPI Analytics
```

**Comment by pixelead0** [comment]
Hola @vaquer , estaremos retomando nuevamente los meetups, presenciales en la cdmx, si aún deses dar esta charla por favor contactame.
