### ISSUE TITLE
Algoritmos genéticos con Python

### ISSUE THREAD

**Issue by bt0DotNinja** [py-mx/Charlas#20]
Descripción:
En esta charla, habló sobre el algoritmos genéticos aplicados, problemas donde se suelen aplicar y demo con el problema de las N reinas.

Objetivo: Incentivar a la audiencia a utilizar técnicas heurísticas cuando el problema lo amerite

Breve reseña sobre mí: Soy un apasionado del software libre y la resolución de problemas complejos.

**Comment by pixelead0** [comment]
Hola @bt0DotNinja, estaremos retomando nuevamente los meetups, presenciales en la cdmx, si aún deses dar esta charla por favor contactame.
