### ISSUE TITLE
¿Los alienígenas nos visitan? Diseño de Experimentos para Ciencia de Datos

### ISSUE THREAD

**Issue by XavierCarrera** [py-mx/Charlas#21]
El diseño de experimentos es una parte fundamental de la estadística y, por ende, de la ciencia de datos. Con esta metodología, podemos formular hipótesis y entender si esta es válida o no. Es por esto que nos permite aceptar o rechazar cualquier idea que tengamos en mente. Y dado lo tan útil que puede ser saber sobre el diseño de experimentos ¿porqué no lo usamos para resolver uno de los misterios más controversiales? ¿Estamos siendo visitados por alienígenas? 

No, este no es un episodio de Tercer Mileno. Usando la teoría del diseño de experimentos, este [tutorial](https://github.com/XavierCarrera/Tutorial-Experimentos-Data-Science) y formulando una hipótesis inicial, utilizaremos un [data set con info de avistamientos](https://www.kaggle.com/NUFORC/ufo-sightings) para averiguar que es lo que los datos nos dicen sobre este fenómeno.

**Comment by pixelead0** [comment]
Hola @XavierCarrera , estaremos retomando nuevamente los meetups, presenciales en la cdmx, si aún deses dar esta charla por favor contactame.
