### ISSUE TITLE
¿Porqué tu mamá debería aprender Python?

### ISSUE THREAD

**Issue by danif70** [py-mx/Charlas#22]
Propuesta: Mi deseo es explicar los beneficios de aprender programación en edades adultas con poco o ningún conocimiento previo de programación (Basada en mi experiencia) y las ventajas de Python como primer lenguaje para acercarse a la programación. También compartiría recursos disponibles (educación online, comunidades).

Objetivo: Motivar a más personas, de mi edad y mayores, a iniciarse en el mundo de la programación con Python.

Breve reseña sobre mi: Estoy en mis 50's, con tres hijos grandes, y hace 7 meses comencé a aprender on line programación con 0 conocimiento previo. Creo firmemente que tod@s deberíamos aprender programación.

Correo electrónico: danielafunes1970@gmail.com

**Comment by pixelead0** [comment]
Hola @danif70 , estaremos retomando nuevamente los meetups, presenciales en la cdmx, si aún deses dar esta charla por favor contactame.

**Comment by danif70** [comment]
Hola Adán, ¿cómo estás? Te cuento que actualmente no trabajo con Python,
estoy dedicada al desarrollo web, pero sigo pensando que Python es una gran
puerta de entrada para la programación. No entiendo bien cuándo serán las
charlas pero cuenta con mi apoyo, envíame la info que sea necesaria.
Un abrazo,
Daniela
