### ISSUE TITLE
Nixtlats: Deep Learning para pronóstico de series de tiempo

### ISSUE THREAD

**Issue by AzulGarza** [py-mx/Charlas#24]
**Nombre de la propuesta**: [Nixtlats](https://github.com/Nixtla/nixtlats): Deep Learning para pronóstico de series de tiempo.

**Descripción**:

El pronóstico de series de tiempo tiene una amplia gama de aplicaciones: finanzas, retail, salud, IoT, etc. Recientemente modelos de deep learning como ESRNN o N-BEATS han demostrado tener performance estado del arte en estas tareas. Nixtlats es una librería de python que hemos desarrollado para facilitar el uso de estos modelos estado del arte a data scientists y developers. Escrita en pytorch, su diseño está enfocado en la usabilidad y reproducibilidad de los experimentos. Para ello, nixtlats cuenta con diversos módulos:

1. Data: contiene datasets de diversas competencias de series de tiempo.
2. Models: incluye modelos estado del arte.
3. Evaluation: posee diversas funciones de pérdida y métricas de evaluación.

**Objetivo**:

1. Introducir a les asistentes a los retos del pronóstico de series de tiempo con deep learning.
2. Describir nixtlats, sus componentes y las mejores prácticas para entrenamiento y despliegue de modelos estado del arte.
3. Reproducción de resultados estado del arte usando nixtlats del modelo ganador de la competencia M4 de series de tiempo (ESRNN).

**Breve reseña sobre ti**:
¡Hola! Soy Fede. Estudié las licenciaturas en Economía y Matemáticas aplicadas en el ITAM. He trabajado para el Banco de México, Banorte (en el área de anaĺítica), en Abraxas (una consultora de ciencia de datos) y actualmente en Nixtla, donde buscamos democratizar el uso de modelos estado del arte para series de tiempo usando machine learning y deep learning. Estoy interesado en el modelado de series de tiempo y sus aplicaciones. Co-desarrollador de [nixtlats](https://github.com/Nixtla/nixtlats).

**Correo electrónico**: fede.garza.ramirez@gmail.com.

**Comment by pixelead0** [comment]
Hola @FedericoGarza , estaremos retomando nuevamente los meetups, presenciales en la cdmx, si aún deses dar esta charla por favor contactame.
