### ISSUE TITLE
Analizando el tráfico en CDMX con python y qgis

### ISSUE THREAD

**Issue by anndroid** [py-mx/Charlas#25]
Python nos brinda la facilidad de realizar diversos análisis al unirse con diferentes herramientas de software. El análisis de datos relacionados con tráfico y su modelado geoespacial es parte de un proyecto de investigación desarrollado en el Instituto Politécnico Nacional, enfocado en identificar el comportamiento del tráfico en la Ciudad de México, y en la creación de un corpus de datos útil para otras investigaciones enfocadas en la transición de ciudades a ciudades inteligentes.
En el proyecto propuesto se mezclan Python, Postgresql y Quantum GIS para modelar el tráfico de la Ciudad de México. Los datos procesados son obtenidos de Twitter por medio de las bibliotecas de Python. La propuesta resalta el uso de tecnologías open source en el campo de la investigación y en la búsqueda de la implantación de ciudades inteligentes.

CONTACTO:
correo:  mag.sald.p@gmail.com
Twitter:  @SirMagg

**Comment by pixelead0** [comment]
Hola @anndroid, estaremos retomando nuevamente los meetups, presenciales en la cdmx, si aún deses dar esta charla por favor contactame.
