### ISSUE TITLE
El auto ARIMA más rápido de Python: construir benchmarks estadísticos para series de tiempo nunca ha sido más sencillo

### ISSUE THREAD

**Issue by AzulGarza** [py-mx/Charlas#26]
*Nombre de la propuesta*: El auto ARIMA más rápido de Python: construir benchmarks estadísticos para series de tiempo nunca ha sido más sencillo

*Descripción*:

ARIMA es uno de los mejores modelos econométricos, pero implentaciones tradicionales de python son demasiado lentas. En Nixtla implementamos una versión 20x más rápida y con mejor precisión en algunos escenarios. En esta charla mostraremos cómo utilizar auto ARIMA y otros modelos estadísticos para el pronóstico de series de tiempo usando StatForecast (github.com/Nixtla/statsforecast).

*Objetivo*:

Introducir a les asistentes a los retos del pronóstico de series de tiempo.
Describir StatsForecast, sus componentes y las mejores prácticas para entrenamiento y despliegue de modelos estadísticos. 
Mostrar el uso de auto ARIMA, su rapidez y precisión.

*Breve reseña sobre ti*:
¡Hola! Soy Fede. Estudié las licenciaturas en Economía y Matemáticas aplicadas en el ITAM. He trabajado para el Banco de México, Banorte (en el área de anaĺítica), en Abraxas (una consultora de ciencia de datos) y actualmente en Nixtla, donde buscamos democratizar el uso de modelos estado del arte para series de tiempo usando machine learning y deep learning. Estoy interesado en el modelado de series de tiempo y sus aplicaciones. Co-desarrollador de `StatsForecast`.

Correo electrónico: [fede.garza.ramirez@gmail.com](mailto:fede.garza.ramirez@gmail.com).

**Comment by pixelead0** [comment]
Hola @FedericoGarza , estaremos retomando nuevamente los meetups, presenciales en CDMX, si aún deses dar esta charla por favor contactame.
