### ISSUE TITLE
chit-chat: Representaciones fonéticas con python

### ISSUE THREAD

**Issue by umoqnier** [py-mx/Charlas#30]
# chit-chat: Representaciones fonéticas con python

## Descripción

¿Te has preguntado que estudia la fonética? ¿Que significan los simbolitos del *International Phonetic Alphabet (IPA)*? y más importante ¿Cómo manipular estos tipos de datos para crear aplicaciones con python?
En esta charla desarrollaremos aplicaciones simples usando datasets con texto en representación fonética y aplicando conceptos sobre fonética en un nivel introductorio.

Ahora si que, pasa la voz :speaking_head:  

## Objetivo

- Los asistentes entenderan los principios básicos de fonología y que es un alfabeto fonético
- Obtención y manipulacióin de datasets disponibles en GitHub
    - https://github.com/open-dict-data/ipa-dict 
- Aplicar estos datos para resolver tareas especificas

## Breve reseña sobre ti

Diego Barriga, Ingeniero en computación por la UNAM, trabajo con NLP y lenguas indigenas mexicanas. Es parte de Laboratorio de Investigacion y Desarrollo de Software Libre, Comunidad Elotl y actualmete desempeña un puesto como MLOps en mercado libre. Promotor de la cultura libre, la privacidad, neovim y de andar en bicicleta sin frenos :)

## Correo electrónico: umoqnier@riseup.net

**Comment by pixelead0** [comment]
Charla agendada en el meetup de septiembre 2024
https://github.com/PythonMexico/python-cdmx-charlas/
