### ISSUE TITLE
Conceptos básicos de redes neuronales

### ISSUE THREAD

**Issue by danvergara** [py-mx/Charlas#4]
Me gustaría explicar conceptos básicos de redes neuronales como: neurona, layers, funciones de activación, fordward propagation, backward propagation, etc. Usando ejemplos escritos en jupyter notebook. También como gestionar el workspace usando anaconda.
Creo que me tomaría 30-40 minutos.

**Comment by mayela** [comment]
Gracias por la charla Danny!
