### ISSUE TITLE
Algunos proyectos de diseño gráfico y Python

### ISSUE THREAD

**Issue by technical-exercise** [py-mx/Charlas#5]
### Nombre de la propuesta

Algunos proyectos de diseño gráfico y Python

### Descripción

Entre los años 2007-2012 he participado en la iniciativa "Open Source Publishing" (OSP) que propone realizar diseño gráfico usando exclusivamente software libre. Durante la charla se hablará del uso de Python en algunos de los proyectos en los que he participado al interior de OSP durante esos años. Entre otras cosas, hemos utilizado Python como una de las herramientas para generar libros, posters, y tipografías.

### Objetivo

1. Compartir los proyectos con la comunidad de Python en cdmx.

2. Repasar algunas de las herramientas de diseño gráfico con software libre

3. Mirar al pasado de algunas API's

4. Discutir sobre estos proyectos con la comunidad

### Breve reseña sobre ti

He estudiado en la Facultad de Ciencias en Ciudad Universitaria y en el Piet Zwart Institute en Rotterdam. Desde el 2008 he trabajado como desarrollador con una variedad relativamente amplia de colegas y proyectos. Hasta donde es posible, uso GNU/Linux en mi vida personal y profesional.

**Comment by pixelead0** [comment]
Podemos apuntar tu charla en el meetup del 12/Jun/2019 en Red Hat.

**Comment by technical-exercise** [comment]
Gracias por tu mensaje, @pixelead0 

Me encantaría si la charla se pudiera incluir en el meetup del 12/Jun/2019.

Dime cualquier comentario, o pregunta que tengas.

Saludos!

**Comment by pixelead0** [comment]
Apuntado en el evento de Junio.
https://www.meetup.com/es-ES/__PyMX__/events/262097528/

**Comment by mayela** [comment]
Gracias por la charla @technical-exercise! :tada:
