### ISSUE TITLE
Construyendo una API GraphQL con Django

### ISSUE THREAD

**Issue by alfonsorodrigo** [py-mx/Charlas#6]
Hola buenos días, me gustaría dar una pequeña platica de como podemos integrar GraphQL con Django, y tocar los siguientes puntos:

1.- Esquemas de datos usando la biblioteca Graphene
2.- Queries & ObjectTypes
3.- Resolvers
4.- InputFields and InputObjectTypes
5.- Mutations

**Comment by mayela** [comment]
La programaremos para una de las reuniones de Julio. Gracias @alfonsorodrigo, te contactamos pronto para los detalles.

**Comment by mayela** [comment]
Gracias por la charla @alfonsorodrigo!
