### ISSUE TITLE
Uso de un ORM ligero en Python para funciones Lambda en AWS

### ISSUE THREAD

**Issue by haunterck** [py-mx/Charlas#7]
Hola, buenas noches.

Nombre de la propuesta: Uso de un ORM ligero en Python para funciones Lambda en AWS

Descripción: La propuesta de la plática es hablar acerca del uso de un ORM ligero llamado Peewee el cual es muy sencillo y rápido de utilizar, así como explicar y ejemplificar cuándo, para qué y cómo se puede utilizar y los grandes beneficios que tiene , sobre todo por la pequeña curva de aprendizaje del mismo. También se dará un breve caso de uso como lo es la utilidad que tiene en la creación de funciones Lambda de AWS.

Objetivo: Dar a conocer su gran utilidad que puede llegar a tener en casos en donde no es requerido por no tratarse de un gran proyecto/tarea pero que no por ello deja de ser interesante tenerlo en mente como opción debido a su gran facilidiad de implementación.

Breve reseña sobre ti: Soy un fanñatico de la tecnología, así como un gran gusto e interés por el lenguaje Python. Me encanta compartir conocimiento y experiencias que he tenido a lo largo de mi carrera profesional.

Mi correo es: haunterck@gmail.com

**Comment by mayela** [comment]
Gracias por la charla @haunterck!
