### ISSUE TITLE
Crea visualizaciones interactivas con Holoviews

### ISSUE THREAD

**Issue by RaulPL** [py-mx/Charlas#8]
Nombre de la propuesta: Crea visualizaciones interactivas con Holoviews

Descripción: Quiero mostrar un análisis que preparé sobre acciendentes de autos en la CDMX, 
enseñaré cuáles fueron las preguntas que me interesaba resolver con los datos y lo haré usando algunas de mis bibliotecas favoritas para visualizar información.

Objetivo: El objetivo de la plática es dar a conocer herramientas que pueden facilitar la exploración de datos. En particular me gustaría mostrar bokeh, holoviews, Panel y mybinder.

Breve reseña sobre ti: Soy Raúl Peralta, trabajo entre desarrollo de  software y ciencia de datos, y me encanta programar en python =P.

Correo electrónico: raulpl25@gmail.com

Twitter: @tnak25

**Comment by mayela** [comment]
Gracias por la charla @RaulPL!
