### ISSUE TITLE
Construyendo pipelines de datos con Python

### ISSUE THREAD

**Issue by monizamudio** [py-mx/Charlas#9]
Nombre de la propuesta: Construyendo pipelines de datos con Python

Descripción: Quiero hablar sobre los casos de uso de pipelines de datos y dar un ejemplo de pipeline implementado en Luigi y en Airflow.

Objetivo: El objetivo de la charla es platicar sobre las ventajas de construir pipelines de datos y dar a conocer Luigi y Airflow, dos herramientas que se pueden utilizar para hacerlo.

Breve reseña sobre ti: Soy Mónica Zamudio. Estudié Economía en el ITAM. He trabajado en distintos proyectos de ciencia de datos como analista, el último siendo el Laboratorio de Datos de SEDESOL. Actualmente soy ingeniera de datos en OPI Analytics. Entre mis áreas de interés están sistemas distribuidos, sistemas operativos (particularmente Linux), teoría de juegos + teoría de redes y tecnología cívica.

Correo electrónico: monzalo14@gmail.com

**Comment by monizamudio** [comment]
Levanté este issue con mi username de la chamba, pero el personal es @monzalo14. No tengo muchos repos míos que estén en Python y sean públicos, pero igual y es relevante para algo (: 

Ah, y mi usuario de twitter es @monnzl, jaja

**Comment by mayela** [comment]
Gracias por la propuesta @monizamudio! Alguien del equipo de organizadores se pondrá en contacto contigo. Saludos

**Comment by mayela** [comment]
Gracias por la charla @monzalo14. Estuvo muy buena. :tada: 
Esperamos que continues participando en las reuniones como asistente o presentadora.
